version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  publish:
    resource_class: small
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: NPM publish
          command: npm publish

workflows:
  test-then-publish:
    jobs:
      - node/test:
          pkg-manager: yarn
          matrix:
            parameters:
              version:
                - 13.11.0
                - 12.16.0
                - 10.19.0
      - publish:
          context: npm-demo
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
